"use strict";(self.webpackChunkreact_papercss_design=self.webpackChunkreact_papercss_design||[]).push([[6329],{40557:function(o,a,e){var n;e.r(a),e.d(a,{demos:function(){return l}});var r=e(17061),s=e.n(r),p=e(17156),I=e.n(p),d=e(67294),x=e(80326),u=e(12276),l={"src-navbar-demo-navbarbase":{component:d.memo(d.lazy(function(){return e.e(2433).then(e.bind(e,21585))})),asset:{type:"BLOCK",id:"src-navbar-demo-navbarbase",refAtomIds:[],dependencies:{"index.tsx":{type:"FILE",value:e(82233).Z},react:{type:"NPM",value:"18.3.1"},"react-papercss-design":{type:"NPM",value:"0.1.0"}},entry:"index.tsx",title:"Basic",description:"Configurable navigation menu"},context:{react:n||(n=e.t(d,2)),"react-papercss-design":u},renderOpts:{compile:function(){var v=I()(s()().mark(function i(){var c,m=arguments;return s()().wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,e.e(7335).then(e.bind(e,37335));case 2:return t.abrupt("return",(c=t.sent).default.apply(c,m));case 3:case"end":return t.stop()}},i)}));function _(){return v.apply(this,arguments)}return _}()}}}},30936:function(o,a,e){e.r(a),e.d(a,{texts:function(){return r}});var n=e(80326);const r=[{value:"A navigation menu list that provides navigation for pages and functionality",paraId:0,tocIndex:0},{value:"Reference: ",paraId:1,tocIndex:0},{value:"Navbar",paraId:1,tocIndex:0},{value:"Property",paraId:2,tocIndex:4},{value:"Description",paraId:2,tocIndex:4},{value:"Type",paraId:2,tocIndex:4},{value:"Default",paraId:2,tocIndex:4},{value:"brand",paraId:2,tocIndex:4},{value:"Title or Logo",paraId:2,tocIndex:4},{value:"string | React.ReactNode",paraId:2,tocIndex:4},{value:"-",paraId:2,tocIndex:4},{value:"bordered",paraId:2,tocIndex:4},{value:"Whether to show border",paraId:2,tocIndex:4},{value:"boolean",paraId:2,tocIndex:4},{value:"true",paraId:2,tocIndex:4},{value:"fixed",paraId:2,tocIndex:4},{value:"Whether fixed at top",paraId:2,tocIndex:4},{value:"boolean",paraId:2,tocIndex:4},{value:"true",paraId:2,tocIndex:4},{value:"splitNav",paraId:2,tocIndex:4},{value:"Whether to split navigation",paraId:2,tocIndex:4},{value:"boolean",paraId:2,tocIndex:4},{value:"true",paraId:2,tocIndex:4},{value:"navbarItems",paraId:2,tocIndex:4},{value:"Content on the right side of navbar",paraId:2,tocIndex:4},{value:"NavbarItem[]",paraId:3,tocIndex:4},{value:"-",paraId:2,tocIndex:4},{value:"Property",paraId:4,tocIndex:5},{value:"Description",paraId:4,tocIndex:5},{value:"Type",paraId:4,tocIndex:5},{value:"Default",paraId:4,tocIndex:5},{value:"label",paraId:4,tocIndex:5},{value:"Text content of nav item",paraId:4,tocIndex:5},{value:"string",paraId:4,tocIndex:5},{value:"-",paraId:4,tocIndex:5},{value:"Supports all other attributes of the ",paraId:5,tocIndex:5},{value:"a",paraId:5,tocIndex:5},{value:" tag, such as ",paraId:5,tocIndex:5},{value:"href",paraId:5,tocIndex:5},{value:", ",paraId:5,tocIndex:5},{value:"target",paraId:5,tocIndex:5},{value:", etc.",paraId:5,tocIndex:5}]},82233:function(o,a){a.Z=`import React from 'react';
import type { NavbarItem } from 'react-papercss-design';
import { Navbar } from 'react-papercss-design';

const App: React.FC = () => {
  const navbarItems: NavbarItem[] = [
    { label: 'Documentation', href: 'https://www.getpapercss.com/docs/' },
    { label: 'About', href: 'https://www.getpapercss.com/about/' },
    { label: 'Github', href: 'https://github.com/rhyneav/papercss' },
  ];

  return <Navbar brand="Get PaperCSS" navbarItems={navbarItems} />;
};

export default App;
`}}]);
